name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '21'

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Kita pakai versi 24 agar jauh melampaui syarat minimum

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/cli @capacitor/android
          npm run build

      - name: Capacitor Sync
        run: |
          # Sekarang Node sudah versi 24, perintah ini pasti jalan
          npx cap sync android

      - name: Build with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: airdroid-clone-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

